In [0]:
import torch
import numpy as np

In [0]:
x = torch.Tensor(5,3) #초기화되지 않은 행렬 생성
print(x)

tensor([[2.6566e-36, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 6.1657e-44],
        [4.2888e-08, 1.0683e-05, 5.4370e+22],
        [2.6977e-09, 5.3534e+22, 2.5640e-09],
        [2.6807e-09, 5.2651e+22, 0.0000e+00]])


In [0]:
y = torch.rand(5,3) #무작위로 초기화된 행렬 생성
print(y)

tensor([[0.1053, 0.1408, 0.4268],
        [0.5129, 0.0943, 0.4094],
        [0.4853, 0.8363, 0.8109],
        [0.2513, 0.3796, 0.4474],
        [0.1926, 0.0265, 0.8939]])


In [0]:
print(x.size()) #행렬 shape 보기
print(x.size(0))
print(x.size(1))

torch.Size([5, 3])
5
3


In [0]:
x1 = torch.rand(5,3)
y1 = torch.rand(5,3)
print(x1+y1)

tensor([[1.6568, 0.9232, 1.5722],
        [1.7276, 0.6779, 0.1845],
        [1.1179, 1.0035, 0.5501],
        [1.0280, 0.9676, 0.4308],
        [0.9072, 1.3729, 1.5193]])


In [0]:
print(torch.add(x1,y1))

tensor([[1.6568, 0.9232, 1.5722],
        [1.7276, 0.6779, 0.1845],
        [1.1179, 1.0035, 0.5501],
        [1.0280, 0.9676, 0.4308],
        [0.9072, 1.3729, 1.5193]])


In [0]:
result = torch.Tensor(5,3)#tensor 생성(초기화 되지 않은)
torch.add(x1,y1,out=result) #Tensor에 덧셈 결과 채워넣기
print(result)

tensor([[1.6568, 0.9232, 1.5722],
        [1.7276, 0.6779, 0.1845],
        [1.1179, 1.0035, 0.5501],
        [1.0280, 0.9676, 0.4308],
        [0.9072, 1.3729, 1.5193]])


In [0]:
y1.add_(x1) #inplace로 덧셈 y1값 변경
print(y1)

tensor([[1.6568, 0.9232, 1.5722],
        [1.7276, 0.6779, 0.1845],
        [1.1179, 1.0035, 0.5501],
        [1.0280, 0.9676, 0.4308],
        [0.9072, 1.3729, 1.5193]])


In [0]:
print(x1)

tensor([[0.7263, 0.0191, 0.5806],
        [0.9443, 0.1834, 0.1363],
        [0.6556, 0.7213, 0.0251],
        [0.8656, 0.6854, 0.3805],
        [0.0761, 0.9548, 0.6396]])


In [0]:
print(x1[:,1])

tensor([0.0191, 0.1834, 0.7213, 0.6854, 0.9548])


In [0]:
print(x1[1:,])

tensor([[0.9443, 0.1834, 0.1363],
        [0.6556, 0.7213, 0.0251],
        [0.8656, 0.6854, 0.3805],
        [0.0761, 0.9548, 0.6396]])


In [0]:
x=torch.randn(4,4)
y = x.view(16) #shape 16row로 변경
z = x.view(-1,8) #8 column, 행은 마음대로 ->(2,8)
print(x.size(), y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [0]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [0]:
b = a.numpy() #tensor를 numpy배열로 변환

In [0]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [0]:
a = 

array([1., 1.], dtype=float32)

In [0]:
import os

lists = os.walk('/content/drive/My Drive/2')
lists

<generator object walk at 0x7fcbc68f37d8>

In [0]:
#폴더 내 파일명들 얻기
for root, dirs, files in os.walk('/content/drive/My Drive/2'):
  for filename in files:
    print(filename)

AttributeError: ignored

In [0]:
import cv2
import numpy as np

def sort_contours(cnts, method="left-to-right"):
    # initialize the reverse flag and sort index
    reverse = False
    i = 0

    # handle if we need to sort in reverse
    if method == "right-to-left" or method == "bottom-to-top":
        reverse = True

    # handle if we are sorting against the y-coordinate rather than
    # the x-coordinate of the bounding box
    if method == "top-to-bottom" or method == "bottom-to-top":
        i = 1

    # construct the list of bounding boxes and sort them from top to
    # bottom
    boundingBoxes = [cv2.boundingRect(c) for c in cnts]
    (cnts, boundingBoxes) = zip(*sorted(zip(cnts, boundingBoxes),
                                        key=lambda b: b[1][i], reverse=reverse))

    # return the list of sorted contours and bounding boxes
    return (cnts, boundingBoxes)

def box_extraction(img_for_box_extraction_path, cropped_dir_path):

    img = cv2.imread(img_for_box_extraction_path, 0)  # Read the image
    (thresh, img_bin) = cv2.threshold(img, 128, 255,
                                      cv2.THRESH_BINARY | cv2.THRESH_OTSU)  # Thresholding the image
    img_bin = 255-img_bin  # Invert the image

    cv2.imwrite("Image_bin.jpg",img_bin)
   
    # Defining a kernel length
    kernel_length = np.array(img).shape[1]//40
     
    # A verticle kernel of (1 X kernel_length), which will detect all the verticle lines from the image.
    verticle_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (1, kernel_length))
    # A horizontal kernel of (kernel_length X 1), which will help to detect all the horizontal line from the image.
    hori_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (kernel_length, 1))
    # A kernel of (3 X 3) ones.
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))

    # Morphological operation to detect verticle lines from an image
    img_temp1 = cv2.erode(img_bin, verticle_kernel, iterations=3)
    verticle_lines_img = cv2.dilate(img_temp1, verticle_kernel, iterations=3)
    cv2.imwrite("verticle_lines.jpg",verticle_lines_img)

    # Morphological operation to detect horizontal lines from an image
    img_temp2 = cv2.erode(img_bin, hori_kernel, iterations=3)
    horizontal_lines_img = cv2.dilate(img_temp2, hori_kernel, iterations=3)
    cv2.imwrite("horizontal_lines.jpg",horizontal_lines_img)

    # Weighting parameters, this will decide the quantity of an image to be added to make a new image.
    alpha = 0.5
    beta = 1.0 - alpha
    # This function helps to add two image with specific weight parameter to get a third image as summation of two image.
    img_final_bin = cv2.addWeighted(verticle_lines_img, alpha, horizontal_lines_img, beta, 0.0)
    img_final_bin = cv2.erode(~img_final_bin, kernel, iterations=2)
    (thresh, img_final_bin) = cv2.threshold(img_final_bin, 128, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)

    # For Debugging
    # Enable this line to see verticle and horizontal lines in the image which is used to find boxes
    cv2.imwrite("img_final_bin.jpg",img_final_bin)
    # Find contours for image, which will detect all the boxes
    contours, hierarchy = cv2.findContours(
        img_final_bin, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    # Sort all the contours by top to bottom.
    (contours, boundingBoxes) = sort_contours(contours, method="top-to-bottom")

    idx = 0
    for c in contours:
        # Returns the location and width,height for every contour
        x, y, w, h = cv2.boundingRect(c)

        # If the box height is greater then 20, widht is >80, then only save it as a box in "cropped/" folder.
        if (w > 80 and h > 20) and w > 3*h:
            idx += 1
            new_img = img[y:y+h, x:x+w]
            cv2.imwrite(cropped_dir_path+str(idx) + '.png', new_img)

    # For Debugging
    # Enable this line to see all contours.
    # cv2.drawContours(img, contours, -1, (0, 0, 255), 3)
    # cv2.imwrite("./Temp/img_contour.jpg", img)


box_extraction("41.jpg", "/content/Cropped/")